# Generated by Django 4.2.4 on 2023-10-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_faces_alter_student_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attendance_files/'),
        ),
    ]
