# Generated by Django 4.2.4 on 2023-10-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attendance_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faces',
        ),
    ]
