# Generated by Django 4.2.4 on 2023-10-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_student_faces'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('attendance_file', models.FileField(blank=True, null=True, upload_to='attendance_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='file',
        ),
        migrations.CreateModel(
            name='ExtractedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('frame_image', models.ImageField(upload_to='extracted_frames/')),
                ('landmarks_json', models.JSONField()),
                ('attendance_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.attendancefile')),
            ],
        ),
    ]
