# Generated by Django 4.2.4 on 2023-11-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_attendancefile_remove_attendance_file_extractedframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='student_faces/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='main_app.student')),
            ],
        ),
    ]
