# Generated by Django 4.2.4 on 2023-11-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_studentfaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfaceimage',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_capture_faces/'),
        ),
        migrations.CreateModel(
            name='TrainedFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_faces', models.ImageField(blank=True, null=True, upload_to='trained_faces/')),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_faces', to='main_app.student')),
            ],
        ),
    ]
