# Generated by Django 4.2.4 on 2023-11-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_studentfaceimage_face_image_trainedfaceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('attendance', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Absent', max_length=20)),
                ('profile_pic', models.ImageField(default='static/images/nobody.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('time', models.TimeField(max_length=50)),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.student_profile')),
            ],
        ),
    ]
