# Generated by Django 4.2.4 on 2023-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_profile_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Absent', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='static/images/nobody.jpg', upload_to=''),
        ),
    ]
