# Generated by Django 4.2.7 on 2023-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0010_relatedmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="training/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
