# Generated by Django 4.2.7 on 2023-11-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0011_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.course",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.session",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_app.student",
            ),
        ),
    ]
