# Generated by Django 4.2.7 on 2023-11-14 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0012_uploadedfile_course_uploadedfile_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="course",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="session",
        ),
    ]
