# Generated by Django 4.2.7 on 2023-11-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0013_remove_uploadedfile_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="extractedframe",
            name="attendance_file",
        ),
        migrations.RemoveField(
            model_name="relatedmodel",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student_attendance",
            name="roll",
        ),
        migrations.RemoveField(
            model_name="student_profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="trainedfaceimage",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="student",
            name="description",
        ),
        migrations.RemoveField(
            model_name="student",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="attendance",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="attendance_files/"
            ),
        ),
        migrations.DeleteModel(
            name="AttendanceFile",
        ),
        migrations.DeleteModel(
            name="ExtractedFrame",
        ),
        migrations.DeleteModel(
            name="RelatedModel",
        ),
        migrations.DeleteModel(
            name="student_attendance",
        ),
        migrations.DeleteModel(
            name="student_profile",
        ),
        migrations.DeleteModel(
            name="TrainedFaceImage",
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="main_app.attendance",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="main_app.student",
            ),
        ),
    ]
