# Generated by Django 4.2.6 on 2023-11-17 09:19

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_studentattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='attendance_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Student_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main_app.models.photo_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_photos', to='main_app.test_student')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendanciees', to='main_app.test_attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendanciees', to='main_app.test_student')),
            ],
        ),
    ]
