# Generated by Django 4.2.6 on 2023-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_test_attendance_test_student_test_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_student_image',
            name='image_no',
            field=models.IntegerField(null=True),
        ),
    ]
