# Generated by Django 4.2.7 on 2023-11-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0018_remove_test_student_image_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test_student_attendance",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="test_student_attendance",
            name="student",
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="date_taken",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="session",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendanciees",
                to="main_app.attendance",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendanciees",
                to="main_app.student",
            ),
        ),
        migrations.DeleteModel(
            name="Test_Attendance",
        ),
        migrations.DeleteModel(
            name="Test_Student_Attendance",
        ),
    ]
