# Generated by Django 4.2.6 on 2023-11-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_attendance_session_alter_attendance_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
    ]
